<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxYHbUN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxYHbUN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxYHbUN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxYHbUN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxYHbUN\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxYHbUN',
    'container.build_id' => 'ab920a95',
    'container.build_time' => 1709156216,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxYHbUN');
