<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Oi9bU7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Oi9bU7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Oi9bU7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Oi9bU7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5Oi9bU7\App_KernelDevDebugContainer([
    'container.build_hash' => '5Oi9bU7',
    'container.build_id' => 'da7d9a64',
    'container.build_time' => 1706535014,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Oi9bU7');
