<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEwb7R9L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEwb7R9L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEwb7R9L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEwb7R9L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEwb7R9L\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ewb7R9L',
    'container.build_id' => '3fb979eb',
    'container.build_time' => 1709146990,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEwb7R9L');
